# Generated by Django 4.0.3 on 2022-03-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('do not show', 'do not show')], max_length=11, null=True),
        ),
    ]
