# Generated by Django 4.0.3 on 2022-04-03 09:59

import DenzelProject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0007_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[DenzelProject.validators.validate_phone_only_numbers]),
        ),
    ]
