# Generated by Django 4.0.3 on 2022-04-08 22:18

import DenzelProject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0010_alter_profile_address_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[DenzelProject.validators.MaxSizeValidatorMB(2)]),
        ),
    ]
