# Generated by Django 4.0.3 on 2022-04-08 21:35

import DenzelProject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0006_alter_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[DenzelProject.validators.MinValidator(3), DenzelProject.validators.MaxValidator(300)], verbose_name='New message'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[DenzelProject.validators.MinValidator(3)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(max_length=30, validators=[DenzelProject.validators.MinValidator(3)]),
        ),
    ]
