# Generated by Django 4.0.3 on 2022-04-08 22:18

import DenzelProject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0007_alter_comment_content_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='', validators=[DenzelProject.validators.MaxSizeValidatorMB(2)]),
        ),
    ]
