# Generated by Django 4.0.3 on 2022-04-10 09:14

import DenzelProject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0011_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='C:\\Users\\Raicho\\Desktop\\Softuni\\Python\\04-WEB\\WebFramework\\DenzelProject\\static\\images\\target.jpg', null=True, upload_to='', validators=[DenzelProject.validators.MaxSizeValidatorMB(2)]),
        ),
    ]
